name = "utility-daily"
main = "functions/api/[[route]].ts"
compatibility_date = "2024-09-19"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "dist"
not_found_handling = "single-page-application"

[[d1_databases]]
binding = "DB"
database_name = "log-harian-db"
database_id = "8402fc5f-8ab5-48a4-bcbf-f6bd66643cd6"
migrations_dir = "migrations"

[vars]
JWT_SECRET = "log_harian_pid_super_secret_dev_key_2026_wib"
